const tauriInvoke = window.__TAURI__?.core?.invoke;
const native = Boolean(tauriInvoke);
const state = { section:'overview', snapshot:null, preview:null, selected:null, catalog:[], search:'', status:native?'Loading .zshrc…':'Browser preview · read-only', error:null, token:'' };
const $=id=>document.getElementById(id);
const official=[['git','Git aliases and completions'],['brew','Homebrew aliases and completions'],['sudo','Prefix the previous command with sudo'],['macos','macOS command aliases'],['docker','Docker completion and aliases'],['extract','Extract common archive formats']];
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function setStatus(s,error=false){state.status=s;$('status-text').textContent=s;$('status-dot').classList.toggle('error',error)}
async function call(request){if(!native)throw new Error('Browser preview is read-only; open the Tauri app to apply changes.');return tauriInvoke('dispatch',{request})}
async function read(){if(!native){state.snapshot={path:'~/.zshrc (fixture)',source:'# Browser preview\nZSH_THEME="robbyrussell"\nplugins=(git brew)\n',values:{theme:'robbyrussell',plugins:['git','brew']},warnings:[],zsh_available:true,platform:'browser preview',plugin_root:'~/.oh-my-zsh/custom/plugins'};state.catalog=official.map(([name,summary])=>({name,summary,kind:'official',enabled:state.snapshot.values.plugins.includes(name),installed:true,repo:null}));render();return}try{const r=await call({kind:'read'});state.snapshot=r.snapshot;state.catalog=official.map(([name,summary])=>({name,summary,kind:'official',enabled:state.snapshot.values.plugins.includes(name),installed:true,repo:null}));setStatus(`Loaded ${state.snapshot.path}`);render()}catch(e){setStatus(e.message,true);render()}}
function title(){return {overview:['Overview','Review your shell setup before making a change.'],configuration:['Configuration','Edit only the safe, recognized values in ~/.zshrc.'],discover:['Discover','Find official Oh My Zsh plugins and GitHub repositories.'],updates:['Updates','Review commit changes before applying them.'],activity:['Activity','Backups and operation results from this app.']}[state.section]}
function render(){const [t,sub]=title();$('page-title').textContent=t;$('page-subtitle').textContent=sub;$('global-search').value=state.search;$('global-search').style.display=state.section==='discover'?'block':'none';({overview:overview,configuration:configuration,discover:discover,updates:updates,activity:activity}[state.section])()}
function overview(){const s=state.snapshot;const warnings=s?.warnings||[];$('content').innerHTML=`<div class="page-header"><h2>Overview</h2><p>A calm place to understand your shell before changing it.</p></div><div class="cards"><div class="card"><div class="symbol">▤</div><div class="value">${s?'.zshrc':'Unavailable'}</div><div class="label">Configuration</div></div><div class="card"><div class="symbol">◈</div><div class="value">${s?.values.plugins.length??'—'}</div><div class="label">Enabled plugins</div></div><div class="card"><div class="symbol">↻</div><div class="value">—</div><div class="label">Updates not checked</div></div></div><section class="group"><div class="group-title">Safety</div><div class="group-body"><div class="callout"><span class="check">✓</span><span>Every change is previewed, backed up, syntax-checked, and checked for stale edits before Apply.</span></div></div></section>${warnings.length?`<section class="group warning"><div class="group-title">Read-only notice</div><div class="group-body">${warnings.map(esc).join('<br>')}<br><span class="muted">Use the raw editor for shell forms this MVP cannot safely rewrite.</span></div></section>`:''}`}
function configuration(){const s=state.snapshot;if(!s){$('content').innerHTML='<div class="empty"><strong>Configuration unavailable</strong><span>Refresh after the shell environment is ready.</span></div>';return}const v=s.values;$('content').innerHTML=`<div class="page-header"><h2>Configuration</h2><p>${esc(s.path)} · ${s.zsh_available?'zsh syntax validation available':'zsh unavailable; Apply disabled'}</p></div><section class="group"><div class="group-title">Recognized settings</div><div class="group-body"><div class="form-row"><label>Theme</label><input id="theme-input" class="text-input" value="${esc(v.theme)}" /></div><div class="form-row"><label>Enabled plugins</label><input id="plugins-input" class="text-input" value="${esc(v.plugins.join(' '))}" /></div><div class="actions"><button class="secondary" id="preview-config">Preview changes</button>${state.preview?'<button class="primary" id="apply-config">Apply…</button>':''}</div>${state.preview?`<pre class="diff">${diffHTML(state.preview.diff)}</pre>`:''}</div></section><section class="group"><div class="group-title">Raw source</div><div class="group-body"><details><summary>Show exact .zshrc text</summary><pre class="source">${esc(s.source)}</pre></details></div></section>`;$('preview-config').onclick=previewConfig;if($('apply-config'))$('apply-config').onclick=()=>confirmApply('Apply .zshrc changes?','A backup is created and zsh -n runs before replacement.',applyPreview)}
async function previewConfig(){const theme=$('theme-input').value.trim();const plugins=$('plugins-input').value.split(/\s+/).filter(Boolean);try{if(!native){setStatus('Browser preview is read-only');return}const r=await call({kind:'preview_config',theme,plugins,expected_source:state.snapshot.source});state.preview=r.preview;setStatus('Preview ready — review before Apply');render()}catch(e){setStatus(e.message,true)}}
async function applyPreview(){await applyAny()};async function applyAny(){if(!state.preview)return;if(!native){setStatus('Browser preview is read-only',true);return}try{const r=await call({kind:'apply',plan_id:state.preview.id});state.preview=null;setStatus(r.applied.status+(r.applied.backup?` · backup ${r.applied.backup}`:''));await read()}catch(e){setStatus(e.message,true)}}
function discover(){const q=state.search.toLowerCase();const rows=state.catalog.filter(p=>!q||`${p.name} ${p.summary} ${p.source||''}`.toLowerCase().includes(q));$('content').innerHTML=`<div class="split"><section class="list-panel">${rows.map((p,i)=>`<button class="plugin-row ${state.selected?.name===p.name?'selected':''}" data-index="${state.catalog.indexOf(p)}"><h3>${esc(p.name)} ${p.enabled?'<span class="badge orange">ENABLED</span>':''}</h3><p>${esc(p.summary)}</p><div class="meta"><span>${esc(p.source||'Oh My Zsh')}</span>${p.installed?'<span class="badge">INSTALLED</span>':''}</div></button>`).join('')||'<div class="empty"><strong>No results</strong><span>Search GitHub or adjust the query.</span></div>'}</section><section class="detail-panel">${state.selected?detail(state.selected):'<div class="empty"><strong>Select a plugin</strong><span>Details and safe actions appear here.</span></div>'}</section></div>`;document.querySelectorAll('[data-index]').forEach(b=>b.onclick=()=>{state.selected=state.catalog[+b.dataset.index];render()});if($('github-search'))$('github-search').onclick=searchGitHub;if($('plugin-enable'))$('plugin-enable').onclick=togglePlugin;if($('plugin-action'))$('plugin-action').onclick=()=>previewPlugin(state.selected.installed?'update':'install');if($('plugin-remove'))$('plugin-remove').onclick=()=>previewPlugin('remove');if($('apply-plugin'))$('apply-plugin').onclick=()=>confirmApply('Apply plugin operation?',state.preview.detail,applyAny);if($('cancel-preview'))$('cancel-preview').onclick=()=>{state.preview=null;render()}}
function detail(p){const repo=p.repo?`${p.repo.owner}/${p.repo.name}`:'';return`<h2>${esc(p.name)}</h2><p class="summary">${esc(p.summary)}</p><dl class="detail-grid"><dt>Source</dt><dd>${esc(p.source||'Oh My Zsh')}</dd><dt>Repository</dt><dd>${esc(repo||'bundled in ohmyzsh/ohmyzsh')}</dd><dt>Current SHA</dt><dd>${esc(p.current||'Not recorded')}</dd><dt>Available SHA</dt><dd>${esc(p.available||'Check before update')}</dd><dt>License</dt><dd>${esc(p.license||'Verified when fetched')}</dd></dl><hr><div class="actions">${p.kind==='github'?`<button class="primary" id="plugin-action">${p.installed?'Review update…':'Review install…'}</button>`:'<button class="primary" id="plugin-enable">'+(p.enabled?'Disable':'Enable')+'</button>'}${p.installed&&p.kind==='github'?'<button class="secondary" id="plugin-enable">'+(p.enabled?'Disable':'Enable')+'</button><button class="secondary" id="plugin-remove">Review uninstall…</button>':''}</div>${state.preview&&state.preview.files.some(f=>f.includes(p.name))?`<pre class="diff">${diffHTML(state.preview.diff)}\n\n${esc(state.preview.detail)}</pre><div class="actions"><button class="primary" id="apply-plugin">Apply…</button><button class="secondary" id="cancel-preview">Cancel</button></div>`:''}<p class="hint">No plugin code or install script is sourced by this app. Apply is always a separate confirmation.</p>`}
async function searchGitHub(){const q=state.search.trim();if(!q)return;try{setStatus('Searching GitHub…');const r=await call({kind:'search',query:q});for(const x of r.search.items){const existing=state.catalog.find(p=>p.name===x.repo.name&&p.repo?.owner===x.repo.owner);if(!existing)state.catalog.push({name:x.repo.name,summary:x.summary,source:`GitHub · ${`${x.repo.owner}/${x.repo.name}`}`,kind:'github',installed:false,enabled:false,repo:x.repo,license:x.license,available:x.updated})}setStatus(`GitHub checked · remaining ${r.search.remaining??'unknown'}`);render()}catch(e){setStatus(e.message,true)}}
async function previewPlugin(operation,p=state.selected){if(!p?.repo){setStatus('Bundled plugin actions only change .zshrc; third-party install needs a GitHub repository.',true);return}try{const r=await call({kind:'preview_plugin',operation,owner:p.repo.owner,repository:p.repo.name});state.preview=r.preview;setStatus('Review the commit and diff before Apply');render()}catch(e){setStatus(e.message,true)}}
async function togglePlugin(){const p=state.selected;if(!p)return;const names=state.snapshot.values.plugins.filter(n=>n!==p.name);if(!p.enabled)names.push(p.name);state.section='configuration';state.snapshot.values.plugins=names;render()}
function diffHTML(s){return esc(s).split('\n').map(x=>x.startsWith('+')?`<span class="add">${x}</span>`:x.startsWith('-')?`<span class="remove">${x}</span>`:x).join('\n')}
function updates(){$('content').innerHTML='<div class="page-header"><h2>Updates</h2><p>Updates appear after checking selected GitHub repositories.</p></div><div class="empty"><strong>No update check yet</strong><span>Open Discover, select a repository, then Review update.</span></div>'}
async function activity(){let rows=[];if(native)try{rows=(await call({kind:'history'})).history||[]}catch{}$('content').innerHTML=`<div class="page-header"><h2>Activity</h2><p>Every applied change leaves a local record.</p></div>${rows.length?rows.map(x=>`<section class="group"><div class="group-title">${esc(x.operation)} · ${esc(x.status)}</div><div class="group-body"><span class="muted">${esc(x.at)}</span><br>${esc(x.files.join('\n'))}${x.backup?`<br><span class="muted">Backup: ${esc(x.backup)}</span>`:''}</div></section>`).join(''):'<div class="empty"><strong>No activity yet</strong><span>Applied operations will appear here.</span></div>'}`}
function confirmApply(title,message,fn){const d=$('confirm-dialog');$('confirm-title').textContent=title;$('confirm-message').textContent=message;d.showModal();d.addEventListener('close',async function h(){d.removeEventListener('close',h);if(d.returnValue==='confirm')await fn()},{once:true})}
$('global-search').oninput=e=>{state.search=e.target.value;render()};$('global-search').onkeydown=e=>{if(e.key==='Enter'&&state.section==='discover')searchGitHub()};$('refresh-button').onclick=read;$('settings-button').onclick=()=>{$('settings-dialog').showModal()};$('settings-form').onsubmit=async e=>{if(e.submitter?.value!=='save')return;try{if(!native)throw Error('Browser preview cannot store credentials');await call({kind:'set_token',token:$('github-token').value.trim()});setStatus('GitHub token saved in OS credential store')}catch(x){setStatus(x.message,true)}};document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{state.section=b.dataset.section;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x===b));render()});read();
