const tauriInvoke = window.__TAURI__?.core?.invoke;
const native = Boolean(tauriInvoke);
function readPreference(key, fallback){try{return localStorage.getItem(`ohmyzsh-gui.${key}`)||fallback}catch{return fallback}}
function savePreference(key, value){try{localStorage.setItem(`ohmyzsh-gui.${key}`,value)}catch{} }
const state = { section:'overview', snapshot:null, preview:null, selected:null, catalog:[], search:'', status:native?'Loading .zshrc…':'Browser preview · read-only', error:null, token:'', updates:null, updatesLoading:false, sort:'stars', sourceFilter:'all', installFilter:'all', recommendedLoaded:false, recommendationsLoading:false, language:readPreference('language','auto'), appearance:readPreference('appearance','system'), glass:readPreference('glass','on')!=='off' };
const $=id=>document.getElementById(id);
const official=[['git','Git aliases and completions'],['brew','Homebrew aliases and completions'],['sudo','Prefix the previous command with sudo'],['macos','macOS command aliases'],['docker','Docker completion and aliases'],['extract','Extract common archive formats']];
const copy={en:{
  'nav.overview':'Overview','nav.installed':'Installed','nav.configuration':'Configuration','nav.discover':'Discover','nav.updates':'Updates','nav.activity':'Activity','nav.settings':'Settings',
  'title.overview':'Overview','title.installed':'Installed','title.configuration':'Configuration','title.discover':'Discover','title.updates':'Updates','title.activity':'Activity',
  'subtitle.overview':'Review your shell setup before making a change.','subtitle.installed':'Manage plugins already present on this device.','subtitle.configuration':'Edit only the safe, recognized values in ~/.zshrc.','subtitle.discover':'Find official Oh My Zsh plugins and GitHub repositories.','subtitle.updates':'Review commit changes before applying them.','subtitle.activity':'Backups and operation results from this app.',
  'settings.title':'Settings','settings.language':'Language','settings.appearance':'Appearance','settings.liquidGlass':'Liquid Glass materials','settings.glassHint':'Uses translucent materials where supported and falls back to solid surfaces when unavailable.','settings.githubToken':'GitHub token','settings.optional':'optional','settings.tokenPrivate':'Token status is private to this app.','settings.tokenHint':'Without a token, GitHub search still works with public rate limits. The token stays local to this app. Save an empty value to remove it.','settings.checkingToken':'Checking token status…','settings.tokenConfigured':'Token is configured in the OS credential store','settings.tokenNone':'No token configured; anonymous GitHub access is active','settings.tokenUnavailable':'Credential store unavailable; anonymous access is active','settings.preferencesSaved':'Preferences saved',
  'common.cancel':'Cancel','common.apply':'Apply','common.save':'Save','common.auto':'Auto (System)','common.light':'Light','common.dark':'Dark','common.english':'English','common.chinese':'简体中文',
  'discover.source':'Source','discover.allSources':'All sources','discover.official':'Oh My Zsh','discover.github':'GitHub','discover.availability':'Availability','discover.allPlugins':'All plugins','discover.available':'Available to install','discover.installed':'Installed','discover.sort':'Sort','discover.stars':'Most stars','discover.updated':'Recently updated','discover.name':'Name','discover.loading':'Loading GitHub recommendations…','discover.result':'result','discover.results':'results','discover.metadata':'GitHub results include live stars, license, description, and update time',
  'confirm.title':'Apply change?'
},zh:{
  'nav.overview':'概览','nav.installed':'已安装','nav.configuration':'配置','nav.discover':'发现','nav.updates':'更新','nav.activity':'活动','nav.settings':'设置',
  'title.overview':'概览','title.installed':'已安装','title.configuration':'配置','title.discover':'发现','title.updates':'更新','title.activity':'活动',
  'subtitle.overview':'在修改前查看你的 Shell 配置。','subtitle.installed':'管理此设备上已有的插件。','subtitle.configuration':'只编辑 ~/.zshrc 中安全且已识别的配置。','subtitle.discover':'查找官方 Oh My Zsh 插件和 GitHub 仓库。','subtitle.updates':'在应用更新前查看提交变更。','subtitle.activity':'查看备份和操作记录。',
  'settings.title':'设置','settings.language':'语言','settings.appearance':'外观','settings.liquidGlass':'Liquid Glass 材质','settings.glassHint':'在支持的环境使用半透明材质，不支持时自动回退为实色界面。','settings.githubToken':'GitHub Token','settings.optional':'可选','settings.tokenPrivate':'Token 状态仅对本应用可见。','settings.tokenHint':'不配置 Token 也可以搜索 GitHub，但会受公开接口频率限制。Token 只保存在本机，保存空值即可移除。','settings.checkingToken':'正在检查 Token 状态…','settings.tokenConfigured':'Token 已保存在系统凭据库','settings.tokenNone':'未配置 Token，当前使用匿名 GitHub 访问','settings.tokenUnavailable':'系统凭据库不可用，当前使用匿名访问','settings.preferencesSaved':'设置已保存',
  'common.cancel':'取消','common.apply':'应用','common.save':'保存','common.auto':'跟随系统','common.light':'浅色','common.dark':'深色','common.english':'English','common.chinese':'简体中文',
  'discover.source':'来源','discover.allSources':'全部来源','discover.official':'Oh My Zsh','discover.github':'GitHub','discover.availability':'可用状态','discover.allPlugins':'全部插件','discover.available':'可安装','discover.installed':'已安装','discover.sort':'排序','discover.stars':'Stars 优先','discover.updated':'最近更新','discover.name':'名称','discover.loading':'正在加载 GitHub 推荐…','discover.result':'个结果','discover.results':'个结果','discover.metadata':'GitHub 结果包含实时 stars、许可证、说明和更新时间',
  'confirm.title':'应用更改？'
}};
function locale(){return state.language==='auto'?(navigator.language||'').toLowerCase().startsWith('zh')?'zh':'en':state.language}
function t(key){return copy[locale()][key]||copy.en[key]||key}
function translateStatic(){document.documentElement.lang=locale()==='zh'?'zh-CN':'en';document.querySelectorAll('[data-i18n]').forEach(el=>{el.textContent=t(el.dataset.i18n)})}
function applyPreferences(){const theme=state.appearance==='system'?'':state.appearance;document.documentElement.dataset.theme=theme;document.documentElement.classList.toggle('glass-enabled',state.glass);document.documentElement.style.colorScheme=theme||'normal';translateStatic()}

function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function starIcon(){return '<svg class="meta-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="m12 2.8 2.78 5.63 6.22.9-4.5 4.38 1.06 6.2L12 17l-5.56 2.91 1.06-6.2L3 9.33l6.22-.9L12 2.8Z"/></svg>'}
function starMetric(value){return value?`<span class="metric" title="GitHub stars">${starIcon()}<span>${Number(value).toLocaleString()}</span></span>`:''}
function formatDate(value){if(!value)return 'Not checked';const date=new Date(value);return Number.isNaN(date.getTime())?String(value):new Intl.DateTimeFormat(undefined,{dateStyle:'medium'}).format(date)}
function setStatus(s,error=false){state.status=s;$('status-text').textContent=s;$('status-dot').classList.toggle('error',error)}
async function call(request){if(!native)throw new Error('Browser preview is read-only; open the Tauri app to apply changes.');return tauriInvoke('dispatch',{request})}
function customCatalog(snapshot){const info=snapshot.installed_custom_info||[];return (snapshot.installed_custom||[]).map(name=>{const x=info.find(v=>v.name===name)||{};const hasRepo=Boolean(x.repo);return {name,summary:hasRepo?'Installed GitHub plugin':'Installed custom plugin',source:hasRepo?`GitHub · ${x.repo.owner}/${x.repo.name}`:'Local custom checkout',kind:hasRepo?'github':'local',installed:true,enabled:snapshot.values.plugins.includes(name),repo:x.repo||{owner:'local',name},current:x.current_sha||null,stars:0,updated:null}})}
async function read(){if(!native){state.snapshot={path:'~/.zshrc (fixture)',source:'# Browser preview\nZSH_THEME="robbyrussell"\nplugins=(git brew)\n',values:{theme:'robbyrussell',plugins:['git','brew']},warnings:[],zsh_available:true,platform:'browser preview',plugin_root:'~/.oh-my-zsh/custom/plugins',installed_custom:[],installed_custom_info:[]};state.catalog=official.map(([name,summary])=>({name,summary,kind:'official',enabled:state.snapshot.values.plugins.includes(name),installed:true,repo:null,stars:0,updated:null}));state.catalog.push(...customCatalog(state.snapshot));render();return}try{const r=await call({kind:'read'});state.snapshot=r.snapshot;state.catalog=official.map(([name,summary])=>({name,summary,kind:'official',enabled:state.snapshot.values.plugins.includes(name),installed:true,repo:null,stars:0,updated:null}));state.catalog.push(...customCatalog(state.snapshot));setStatus(`Loaded ${state.snapshot.path}`);render()}catch(e){setStatus(e.message,true);render()}}
function title(){return {overview:[t('title.overview'),t('subtitle.overview')],installed:[t('title.installed'),t('subtitle.installed')],configuration:[t('title.configuration'),t('subtitle.configuration')],discover:[t('title.discover'),t('subtitle.discover')],updates:[t('title.updates'),t('subtitle.updates')],activity:[t('title.activity'),t('subtitle.activity')]}[state.section]}
function render(){applyPreferences();const [t,sub]=title();$('page-title').textContent=t;$('page-subtitle').textContent=sub;$('global-search').value=state.search;$('global-search').style.display=state.section==='discover'?'block':'none';$('updates-count').textContent=state.updates?.length??0;({overview:overview,installed:installed,configuration:configuration,discover:discover,updates:updates,activity:activity}[state.section])()}
function overview(){const s=state.snapshot;const warnings=s?.warnings||[];$('content').innerHTML=`<div class="page-header"><h2>Overview</h2><p>A calm place to understand your shell before changing it.</p></div><div class="cards"><div class="card"><div class="symbol">▤</div><div class="value">${s?'.zshrc':'Unavailable'}</div><div class="label">Configuration</div></div><div class="card"><div class="symbol">◈</div><div class="value">${s?.values.plugins.length??'—'}</div><div class="label">Enabled plugins</div></div><div class="card"><div class="symbol">↻</div><div class="value">—</div><div class="label">Updates not checked</div></div></div><section class="group"><div class="group-title">Safety</div><div class="group-body"><div class="callout"><span class="check">✓</span><span>Every change is previewed, backed up, syntax-checked, and checked for stale edits before Apply.</span></div></div></section>${warnings.length?`<section class="group warning"><div class="group-title">Read-only notice</div><div class="group-body">${warnings.map(esc).join('<br>')}<br><span class="muted">Use the raw editor for shell forms this MVP cannot safely rewrite.</span></div></section>`:''}`}
function configuration(){const s=state.snapshot;if(!s){$('content').innerHTML='<div class="empty"><strong>Configuration unavailable</strong><span>Refresh after the shell environment is ready.</span></div>';return}const v=s.values;$('content').innerHTML=`<div class="page-header"><h2>Configuration</h2><p>${esc(s.path)} · ${s.zsh_available?'zsh syntax validation available':'zsh unavailable; Apply disabled'}</p></div><section class="group"><div class="group-title">Recognized settings</div><div class="group-body"><div class="form-row"><label>Theme</label><input id="theme-input" class="text-input" value="${esc(v.theme)}" /></div><div class="form-row"><label>Enabled plugins</label><input id="plugins-input" class="text-input" value="${esc(v.plugins.join(' '))}" /></div><div class="actions"><button class="secondary" id="preview-config">Preview changes</button>${state.preview?'<button class="primary" id="apply-config">Apply…</button>':''}</div>${state.preview?`<pre class="diff">${diffHTML(state.preview.diff)}</pre>`:''}</div></section><section class="group"><div class="group-title">Raw source</div><div class="group-body"><details><summary>Show exact .zshrc text</summary><pre class="source">${esc(s.source)}</pre></details></div></section>`;$('preview-config').onclick=previewConfig;if($('apply-config'))$('apply-config').onclick=()=>confirmApply('Apply .zshrc changes?','A backup is created and zsh -n runs before replacement.',applyPreview)}
function installed(){const rows=state.catalog.filter(p=>p.installed);$('content').innerHTML=`<div class="split"><section class="list-panel">${rows.map((p,i)=>`<button class="plugin-row ${state.selected?.name===p.name?'selected':''}" data-installed="${i}"><h3>${esc(p.name)} ${p.enabled?'<span class="badge orange">ENABLED</span>':''}</h3><p>${esc(p.summary)}</p><div class="meta"><span>${esc(p.source||'Oh My Zsh')}</span><span class="badge">INSTALLED</span></div></button>`).join('')||'<div class="empty"><strong>No plugins installed</strong><span>Discover a plugin to get started.</span></div>'}</section><section class="detail-panel">${state.selected?detail(state.selected):'<div class="empty"><strong>Select an installed plugin</strong><span>Details and safe actions appear here.</span></div>'}</section></div>`;document.querySelectorAll('[data-installed]').forEach(b=>b.onclick=()=>{state.selected=rows[+b.dataset.installed];render()});if($('plugin-enable'))$('plugin-enable').onclick=togglePlugin;if($('plugin-action'))$('plugin-action').onclick=()=>previewPlugin(state.selected.installed?'update':'install');if($('plugin-remove'))$('plugin-remove').onclick=()=>previewPlugin('remove');if($('apply-plugin'))$('apply-plugin').onclick=()=>confirmApply('Apply plugin operation?',state.preview.detail,applyAny);if($('cancel-preview'))$('cancel-preview').onclick=()=>{state.preview=null;render()}}
async function previewConfig(){const theme=$('theme-input').value.trim();const plugins=$('plugins-input').value.split(/\s+/).filter(Boolean);try{if(!native){setStatus('Browser preview is read-only');return}const r=await call({kind:'preview_config',theme,plugins,expected_source:state.snapshot.source});state.preview=r.preview;setStatus('Preview ready — review before Apply');render()}catch(e){setStatus(e.message,true)}}
async function applyPreview(){await applyAny()};async function applyAny(){if(!state.preview)return;if(!native){setStatus('Browser preview is read-only',true);return}try{const r=await call({kind:'apply',plan_id:state.preview.id});state.preview=null;setStatus(r.applied.status+(r.applied.backup?` · backup ${r.applied.backup}`:''));await read()}catch(e){setStatus(e.message,true)}}
function discover(){
  if(native&&!state.recommendedLoaded&&!state.recommendationsLoading){state.recommendationsLoading=true;loadRecommendations()}
  const q=state.search.toLowerCase();
  let rows=state.catalog.filter(p=>{
    const matchesSearch=!q||`${p.name} ${p.summary} ${p.source||''}`.toLowerCase().includes(q);
    const matchesSource=state.sourceFilter==='all'||(state.sourceFilter==='github'&&p.kind==='github')||(state.sourceFilter==='official'&&p.kind==='official');
    const matchesInstall=state.installFilter==='all'||(state.installFilter==='installed'&&p.installed)||(state.installFilter==='available'&&!p.installed);
    return matchesSearch&&matchesSource&&matchesInstall;
  });
  rows=[...rows].sort((a,b)=>{
    if(state.sort==='updated')return (Date.parse(b.updated||'')||0)-(Date.parse(a.updated||'')||0)||a.name.localeCompare(b.name);
    if(state.sort==='name')return a.name.localeCompare(b.name);
    return (b.stars||0)-(a.stars||0)||a.name.localeCompare(b.name);
  });
  $('content').innerHTML=`<div class="discover-controls"><label>${t('discover.source')} <select id="source-filter" class="select-input"><option value="all">${t('discover.allSources')}</option><option value="official">${t('discover.official')}</option><option value="github">${t('discover.github')}</option></select></label><label>${t('discover.availability')} <select id="install-filter" class="select-input"><option value="all">${t('discover.allPlugins')}</option><option value="available">${t('discover.available')}</option><option value="installed">${t('discover.installed')}</option></select></label><label>${t('discover.sort')} <select id="sort-filter" class="select-input"><option value="stars">${t('discover.stars')}</option><option value="updated">${t('discover.updated')}</option><option value="name">${t('discover.name')}</option></select></label>${state.recommendationsLoading?`<span class="muted">${t('discover.loading')}</span>`:''}</div><p class="discover-summary">${rows.length} ${rows.length===1?t('discover.result'):t('discover.results')}${q?` · ${esc(state.search)}`:''} · ${t('discover.metadata')}</p><div class="split"><section class="list-panel">${rows.map(p=>`<button class="plugin-row" data-index="${state.catalog.indexOf(p)}"><h3>${esc(p.name)} ${p.enabled?'<span class="badge orange">ENABLED</span>':''}</h3><p>${esc(p.summary)}</p><div class="meta"><span>${esc(p.source||'Oh My Zsh')}</span>${starMetric(p.stars)}${p.updated?`<span title="Last updated">Updated ${esc(formatDate(p.updated))}</span>`:''}${p.installed?'<span class="badge">INSTALLED</span>':''}</div></button>`).join('')||'<div class="empty"><strong>No results</strong><span>Search GitHub or adjust the filters.</span></div>'}</section><section class="detail-panel">${state.selected?detail(state.selected):'<div class="empty"><strong>Select a plugin</strong><span>Details, stars, license, and safe actions appear here.</span></div>'}</section></div>`;
  $('source-filter').value=state.sourceFilter;$('install-filter').value=state.installFilter;$('sort-filter').value=state.sort;
  $('source-filter').onchange=e=>{state.sourceFilter=e.target.value;render()};$('install-filter').onchange=e=>{state.installFilter=e.target.value;render()};$('sort-filter').onchange=e=>{state.sort=e.target.value;render()};
  document.querySelectorAll('[data-index]').forEach(b=>b.onclick=()=>{state.selected=state.catalog[+b.dataset.index];render()});
  if($('github-search'))$('github-search').onclick=()=>searchGitHub();if($('plugin-enable'))$('plugin-enable').onclick=togglePlugin;if($('plugin-action'))$('plugin-action').onclick=()=>previewPlugin(state.selected.installed?'update':'install');if($('plugin-remove'))$('plugin-remove').onclick=()=>previewPlugin('remove');if($('apply-plugin'))$('apply-plugin').onclick=()=>confirmApply('Apply plugin operation?',state.preview.detail,applyAny);if($('cancel-preview'))$('cancel-preview').onclick=()=>{state.preview=null;render()}
}
function detail(p){const repo=p.repo?`${p.repo.owner}/${p.repo.name}`:'';const remote=p.kind==='github'&&!p.repo?.owner?.startsWith('local');const lifecycle=remote?`<button class="primary" id="plugin-action">${p.installed?'Review update…':'Review install…'}</button>`:'';const enable=p.installed?`<button class="secondary" id="plugin-enable">${p.enabled?'Disable':'Enable'}</button>`:'';const remove=p.installed&&(p.kind==='github'||p.kind==='local')?'<button class="secondary" id="plugin-remove">Review uninstall…</button>':'';return`<h2>${esc(p.name)}</h2><p class="summary">${esc(p.summary)}</p><dl class="detail-grid"><dt>Source</dt><dd>${esc(p.source||'Oh My Zsh')}</dd><dt>Repository</dt><dd>${esc(repo||'bundled in ohmyzsh/ohmyzsh')}</dd><dt>Stars</dt><dd>${p.stars?starMetric(p.stars):'—'}</dd><dt>License</dt><dd>${esc(p.license||'Verified when fetched')}</dd><dt>Updated</dt><dd>${esc(formatDate(p.updated))}</dd><dt>Current SHA</dt><dd>${esc(p.current?p.current.slice(0,8)+'…':'Not recorded')}</dd><dt>Available SHA</dt><dd>${esc(p.available?p.available.slice(0,8)+'…':'Check before update')}</dd></dl><hr><div class="actions">${lifecycle}${enable}${remove}</div>${state.preview&&state.preview.files.some(f=>f.includes(p.name))?`<pre class="diff">${diffHTML(state.preview.diff)}\n\n${esc(state.preview.detail)}</pre><div class="actions"><button class="primary" id="apply-plugin">Apply…</button><button class="secondary" id="cancel-preview">Cancel</button></div>`:''}<p class="hint">No plugin code or install script is sourced by this app. Apply is always a separate confirmation.</p>`}
async function searchGitHub(query=null){const q=(query??state.search).trim()||'zsh plugin';try{setStatus(`Searching GitHub for ${q}…`);const r=await call({kind:'search',query:q});for(const x of r.search.items){const existing=state.catalog.find(p=>p.name===x.repo.name&&p.repo?.owner===x.repo.owner);if(existing){Object.assign(existing,{stars:x.stars,license:x.license,updated:x.updated,available:null})}else state.catalog.push({name:x.repo.name,summary:x.summary,source:`GitHub · ${x.repo.owner}/${x.repo.name}`,kind:'github',installed:false,enabled:false,repo:x.repo,license:x.license,stars:x.stars,updated:x.updated,current:null,available:null})}if(q==='zsh plugin')state.recommendedLoaded=true;setStatus(`GitHub checked · remaining ${r.search.remaining??'unknown'}`);render()}catch(e){state.recommendationsLoading=false;setStatus(e.message,true);render()}}
async function loadRecommendations(){try{await searchGitHub('zsh plugin')}finally{state.recommendationsLoading=false;render()}}
async function previewPlugin(operation,p=state.selected){if(!p?.repo){setStatus('Bundled plugin actions only change .zshrc; third-party install needs a GitHub repository.',true);return}try{const r=await call({kind:'preview_plugin',operation,owner:p.repo.owner,repository:p.repo.name});state.preview=r.preview;setStatus('Review the commit and diff before Apply');render()}catch(e){setStatus(e.message,true)}}
async function togglePlugin(){const p=state.selected;if(!p)return;const names=state.snapshot.values.plugins.filter(n=>n!==p.name);if(!p.enabled)names.push(p.name);state.section='configuration';state.snapshot.values.plugins=names;render()}
function diffHTML(s){return esc(s).split('\n').map(x=>x.startsWith('+')?`<span class="add">${x}</span>`:x.startsWith('-')?`<span class="remove">${x}</span>`:x).join('\n')}
function updates(){if(state.updates===null&&!state.updatesLoading){state.updatesLoading=true;if(native)checkUpdates();else{state.updates=[];state.updatesLoading=false}}const rows=state.updates||[];$('content').innerHTML=`<div class="page-header"><h2>Updates</h2><p>Review commit changes before applying them.</p><button class="secondary" id="refresh-updates">Check for updates</button></div>${state.updatesLoading?'<div class="empty"><strong>Checking GitHub…</strong><span>Comparing installed plugin commits with their recorded remotes.</span></div>':rows.length?`<section class="group"><div class="group-title">Available updates</div><div class="group-body update-list">${rows.map((x,i)=>`<button class="update-row" data-update="${i}"><strong>${esc(x.name)}</strong><span>${esc(x.repo.owner+'/'+x.repo.name)}</span><small>${esc(x.current_sha.slice(0,8)+'…')} → ${esc(x.available_sha.slice(0,8)+'…')}</small><p>${esc(x.summary||'Commit summary unavailable')}</p></button>`).join('')}</div></section>`:'<div class="empty"><strong>No updates found</strong><span>Installed GitHub plugins are already at their recorded remote commit, or no app-managed GitHub plugins exist yet.</span></div>'}`;if($('refresh-updates'))$('refresh-updates').onclick=()=>{state.updates=null;render()};document.querySelectorAll('[data-update]').forEach(b=>b.onclick=()=>{const x=rows[+b.dataset.update];let p=state.catalog.find(y=>y.repo?.owner===x.repo.owner&&y.repo?.name===x.repo.name);if(!p){p={name:x.name,summary:'Installed GitHub plugin',source:`GitHub · ${x.repo.owner}/${x.repo.name}`,kind:'github',installed:true,enabled:state.snapshot.values.plugins.includes(x.name),repo:x.repo,current:x.current_sha,available:x.available_sha};state.catalog.push(p)}else{p.current=x.current_sha;p.available=x.available_sha}state.selected=p;state.section='discover';render()})}
async function checkUpdates(){try{const r=await call({kind:'updates'});state.updates=r.updates||[]}catch(e){setStatus(e.message,true);state.updates=[]}finally{state.updatesLoading=false;render()}}
async function activity(){let rows=[];if(native)try{rows=(await call({kind:'history'})).history||[]}catch{}$('content').innerHTML=`<div class="page-header"><h2>Activity</h2><p>Backups, quarantine paths, and reversible operations from this app.</p></div>${rows.length?rows.map(x=>`<section class="group"><div class="group-title">${esc(x.operation)} · ${esc(x.status)}</div><div class="group-body"><span class="muted">${esc(x.at)}</span>${x.repo?`<br>${esc(x.repo.owner+'/'+x.repo.name)}`:''}${x.commit?`<br>Commit <code>${esc(x.commit)}</code>`:''}${x.previous_commit?`<br>Previous commit <code>${esc(x.previous_commit)}</code>`:''}<br>${esc(x.files.join('\n'))}${x.backup?`<br><span class="muted">Backup: ${esc(x.backup)}</span>`:''}${x.undo_available?`<div class="actions"><button class="secondary" data-undo="${esc(x.id)}">Undo</button></div>`:''}</div></section>`).join(''):'<div class="empty"><strong>No activity yet</strong><span>Applied operations will appear here.</span></div>'}`;document.querySelectorAll('[data-undo]').forEach(b=>b.onclick=()=>confirmApply('Restore this operation?','The app will restore its backup or quarantined checkout after checking the current state.',()=>undoHistory(b.dataset.undo)))}
async function undoHistory(id){if(!native){setStatus('Browser preview is read-only',true);return}try{const r=await call({kind:'undo',history_id:id});setStatus(r.applied.status+(r.applied.backup?` · backup ${r.applied.backup}`:''));await read();render()}catch(e){setStatus(e.message,true)}}
function confirmApply(title,message,fn){const d=$('confirm-dialog');$('confirm-title').textContent=title;$('confirm-message').textContent=message;d.showModal();d.addEventListener('close',async function h(){d.removeEventListener('close',h);if(d.returnValue==='confirm')await fn()},{once:true})}
$('global-search').oninput=e=>{state.search=e.target.value;render()};
$('global-search').onkeydown=e=>{if(e.key==='Enter'&&state.section==='discover')searchGitHub()};
$('refresh-button').onclick=read;
function refreshTokenStatus(){if(!native)return;call({kind:'token_status'}).then(r=>{$('token-status').textContent=r.message==='configured'?t('settings.tokenConfigured'):r.message==='not_configured'?t('settings.tokenNone'):t('settings.tokenUnavailable')}).catch(x=>{$('token-status').textContent=x.message})}
$('settings-button').onclick=()=>{
  translateStatic();
  $('language-select').value=state.language;$('appearance-select').value=state.appearance;$('glass-toggle').checked=state.glass;
  $('settings-dialog').showModal();
  $('token-status').textContent=t('settings.tokenPrivate');
  window.setTimeout(refreshTokenStatus,0);
};
$('language-select').onchange=e=>{state.language=e.target.value;savePreference('language',state.language);render()};
$('appearance-select').onchange=e=>{state.appearance=e.target.value;savePreference('appearance',state.appearance);applyPreferences();render()};
$('glass-toggle').onchange=e=>{state.glass=e.target.checked;savePreference('glass',state.glass?'on':'off');applyPreferences();render()};
$('settings-form').onsubmit=async e=>{if(e.submitter?.value!=='save')return;state.language=$('language-select').value;state.appearance=$('appearance-select').value;state.glass=$('glass-toggle').checked;savePreference('language',state.language);savePreference('appearance',state.appearance);savePreference('glass',state.glass?'on':'off');applyPreferences();if(native)try{await call({kind:'set_token',token:$('github-token').value.trim()});$('token-status').textContent=$('github-token').value.trim()?t('settings.tokenConfigured'):t('settings.tokenNone');setStatus(t('settings.preferencesSaved'))}catch(x){setStatus(x.message,true)}else setStatus(t('settings.preferencesSaved'))};
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{state.section=b.dataset.section;if(state.section==='installed'&&state.selected&&!state.selected.installed)state.selected=null;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x===b));render()});
applyPreferences();
read();
