const invoke = window.__TAURI__?.core?.invoke ?? (async (command, args) => {
  if (command === 'read_zshrc') return { path: '~/.zshrc', source: '# Browser preview\nZSH_THEME="robbyrussell"\nplugins=(git brew)\n', theme: 'robbyrussell', plugins: ['git', 'brew'], zsh_available: true };
  if (command === 'preview_zshrc') return { diff: '--- .zshrc (current)\n+++ .zshrc (preview)\n- plugins=(git brew)\n+ plugins=(git brew zsh-autosuggestions)' };
  if (command === 'apply_zshrc') return { backup: '~/.ohmyzsh-gui/backups/zshrc-preview' };
  if (command === 'github_token_set') return { ok: true };
  return { ok: true };
});

const state = { section: 'overview', config: null, theme: '', plugins: [], diff: '', selectedPlugin: null, catalog: [
  { id: 'git', name: 'git', summary: 'Aliases and completions for Git.', source: 'Oh My Zsh', kind: 'official', installed: false, enabled: false },
  { id: 'brew', name: 'brew', summary: 'Aliases and completions for Homebrew.', source: 'Oh My Zsh', kind: 'official', installed: false, enabled: false },
  { id: 'zsh-autosuggestions', name: 'zsh-autosuggestions', summary: 'Fish-like autosuggestions for zsh.', source: 'GitHub · zsh-users/zsh-autosuggestions', kind: 'github', owner: 'zsh-users', repo: 'zsh-autosuggestions', installed: false, enabled: false },
  { id: 'zsh-syntax-highlighting', name: 'zsh-syntax-highlighting', summary: 'Fish-like syntax highlighting for zsh.', source: 'GitHub · zsh-users/zsh-syntax-highlighting', kind: 'github', owner: 'zsh-users', repo: 'zsh-syntax-highlighting', installed: false, enabled: false }
], githubToken: '' };
const $ = (id) => document.getElementById(id);
const content = $('content');
const titles = { overview: ['Overview', 'Review your shell setup before making a change.'], configuration: ['Configuration', 'Edit the Oh My Zsh values stored in ~/.zshrc.'], discover: ['Discover', 'Find trusted Oh My Zsh and GitHub plugins.'], updates: ['Updates', 'Review commit changes before applying an update.'], activity: ['Activity', 'Backups and operation results from this app.'] };
function setStatus(text, error = false) { $('status-text').textContent = text; $('status-dot').classList.toggle('error', error); }
function escapeHTML(value) { return String(value ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c])); }
function render() { const [title, subtitle] = titles[state.section]; $('page-title').textContent = title; $('page-subtitle').textContent = subtitle; $('global-search').style.display = state.section === 'discover' ? 'block' : 'none'; if (state.section === 'overview') renderOverview(); else if (state.section === 'configuration') renderConfiguration(); else if (state.section === 'discover') renderDiscover(); else if (state.section === 'updates') renderUpdates(); else renderActivity(); }
function renderOverview() { const c = state.config; content.innerHTML = `<div class="page-header"><h2>Overview</h2><p>A calm place to understand your shell before changing it.</p></div><div class="cards"><div class="card"><div class="symbol">▤</div><div class="value">${c ? '.zshrc' : 'Not found'}</div><div class="label">Configuration</div></div><div class="card"><div class="symbol">◈</div><div class="value">${state.plugins.length}</div><div class="label">Enabled plugins</div></div><div class="card"><div class="symbol">↻</div><div class="value">${updateCount()}</div><div class="label">Available updates</div></div></div><section class="group"><div class="group-title">Safety</div><div class="group-body"><div class="callout"><span class="check">✓</span><span>Every change is previewed, backed up, and syntax-checked before replacement.</span></div></div></section>`; }
function renderConfiguration() { content.innerHTML = `<div class="page-header"><h2>Configuration</h2><p>Only the managed values change; the rest of your file stays intact.</p></div><section class="group"><div class="group-title">Appearance</div><div class="group-body"><div class="form-row"><label for="theme-input">Theme</label><input id="theme-input" class="text-input" value="${escapeHTML(state.theme)}" placeholder="robbyrussell" /></div></div></section><section class="group"><div class="group-title">Plugins</div><div class="group-body"><div class="form-row"><label for="plugins-input">Enabled plugins</label><input id="plugins-input" class="text-input" value="${escapeHTML(state.plugins.join(' '))}" placeholder="git brew" /></div><div class="actions"><button class="secondary" id="preview-config">Preview changes</button>${state.diff ? '<button class="primary" id="apply-config">Apply…</button>' : ''}</div>${state.diff ? `<pre class="diff">${formatDiff(state.diff)}</pre>` : ''}</div></section>`; $('theme-input').addEventListener('input', (e) => { state.theme = e.target.value; }); $('plugins-input').addEventListener('input', (e) => { state.plugins = e.target.value.split(/\s+/).filter(Boolean); }); $('preview-config').addEventListener('click', previewConfig); if ($('apply-config')) $('apply-config').addEventListener('click', () => confirmApply('Apply .zshrc changes?', 'A backup will be created and zsh syntax will be checked.', applyConfig)); }
function renderDiscover() { const query = $('global-search').value.trim().toLowerCase(); const rows = state.catalog.filter(p => !query || `${p.name} ${p.summary} ${p.source}`.toLowerCase().includes(query)); if (!state.selectedPlugin || !rows.some(p => p.id === state.selectedPlugin.id)) state.selectedPlugin = rows[0] ?? null; content.innerHTML = `<div class="split"><section class="list-panel">${rows.map(p => `<button class="plugin-row ${state.selectedPlugin?.id === p.id ? 'selected' : ''}" data-plugin="${p.id}"><h3>${escapeHTML(p.name)} ${p.enabled ? '<span class="badge orange">ENABLED</span>' : ''}</h3><p>${escapeHTML(p.summary)}</p><div class="meta"><span>${escapeHTML(p.source)}</span>${p.installed ? '<span class="badge">INSTALLED</span>' : ''}</div></button>`).join('') || '<div class="empty"><div><strong>No plugins found</strong><span>Try another search.</span></div></div>'}</section><section class="detail-panel">${state.selectedPlugin ? pluginDetail(state.selectedPlugin) : '<div class="empty"><div><strong>Select a plugin</strong><span>Details appear here.</span></div></div>'}</section></div>`; document.querySelectorAll('[data-plugin]').forEach((el) => el.addEventListener('click', () => { state.selectedPlugin = state.catalog.find(p => p.id === el.dataset.plugin); render(); })); const action = $('plugin-action'); if (action) action.addEventListener('click', pluginAction); const toggle = $('plugin-toggle'); if (toggle) toggle.addEventListener('click', togglePlugin); const remove = $('plugin-remove'); if (remove) remove.addEventListener('click', () => confirmApply(`Uninstall ${state.selectedPlugin.name}?`, 'The checkout will be removed. Your .zshrc remains unchanged until you review its diff.', async () => { try { await invoke('uninstall_plugin', { owner: state.selectedPlugin.owner || 'ohmyzsh', repository: state.selectedPlugin.repo || state.selectedPlugin.name }); state.selectedPlugin.installed = false; setStatus('Uninstall complete'); render(); } catch (e) { setStatus(`Uninstall failed: ${e}`, true); } })); }
function pluginDetail(p) { const action = p.installed ? 'Update…' : 'Install…'; return `<h2>${escapeHTML(p.name)}</h2><p class="summary">${escapeHTML(p.summary)}</p><dl class="detail-grid"><dt>Source</dt><dd>${escapeHTML(p.source)}</dd><dt>Current commit</dt><dd>${escapeHTML(p.currentCommit || (p.installed ? 'Inspecting…' : 'Not installed'))}</dd><dt>Available commit</dt><dd>${escapeHTML(p.availableCommit || 'Check for updates')}</dd><dt>License</dt><dd>Shown when verified</dd></dl><hr><div class="actions"><button class="primary" id="plugin-action">${action}</button><button class="secondary" id="plugin-toggle">${p.enabled ? 'Disable' : 'Enable'}</button>${p.installed ? '<button class="secondary" id="plugin-remove">Uninstall…</button>' : ''}</div><p class="hint">Install, update, and uninstall always show a preflight summary and require Apply confirmation.</p>`; }
function renderUpdates() { const updates = state.catalog.filter(p => p.installed && p.availableCommit && p.availableCommit !== p.currentCommit); content.innerHTML = `<div class="page-header"><h2>Updates</h2><p>Review current and new commit SHAs before applying.</p></div>${updates.length ? updates.map(p => `<section class="group"><div class="group-title">${escapeHTML(p.name)} <span class="badge orange">UPDATE AVAILABLE</span></div><div class="group-body"><dl class="detail-grid"><dt>Current commit</dt><dd>${escapeHTML(p.currentCommit)}</dd><dt>New commit</dt><dd>${escapeHTML(p.availableCommit)}</dd><dt>Summary</dt><dd>Commit summary is fetched before Apply.</dd></dl><div class="actions"><button class="primary" data-update="${p.id}">Review update…</button></div></div></section>`).join('') : '<div class="empty"><div><strong>Everything is up to date</strong><span>Refresh Discover to check GitHub again.</span></div></div>'}`; document.querySelectorAll('[data-update]').forEach(el => el.addEventListener('click', () => { state.selectedPlugin = state.catalog.find(p => p.id === el.dataset.update); state.section = 'discover'; render(); })); }
function renderActivity() { content.innerHTML = '<div class="page-header"><h2>Activity</h2><p>Backups and operation results will appear here.</p></div><div class="empty"><div><strong>No activity yet</strong><span>Completed operations will be recorded here.</span></div></div>'; }
function formatDiff(diff) { return escapeHTML(diff).split('\n').map(line => line.startsWith('+') ? `<span class="add">${line}</span>` : line.startsWith('-') ? `<span class="remove">${line}</span>` : line).join('\n'); }
function updateCount() { return state.catalog.filter(p => p.availableCommit && p.currentCommit && p.availableCommit !== p.currentCommit).length; }
async function loadConfig() { try { state.config = await invoke('read_zshrc'); state.theme = state.config.theme || ''; state.plugins = state.config.plugins || []; state.catalog.forEach(p => { p.enabled = state.plugins.includes(p.name); p.installed = p.kind === 'official' ? false : p.installed; }); setStatus(`Loaded ${state.config.path}`); } catch (e) { setStatus('Could not read .zshrc', true); } render(); }
async function previewConfig() { try { const result = await invoke('preview_zshrc', { theme: state.theme || null, plugins: state.plugins }); state.diff = result.diff || ''; setStatus('Preview ready — review before applying'); render(); } catch { setStatus('Preview failed', true); } }
function confirmApply(title, message, action) { $('confirm-title').textContent = title; $('confirm-message').textContent = message; const dialog = $('confirm-dialog'); dialog.showModal(); dialog.addEventListener('close', async function handler() { dialog.removeEventListener('close', handler); if (dialog.returnValue === 'confirm') await action(); }, { once: true }); }
async function applyConfig() { try { const result = await invoke('apply_zshrc', { theme: state.theme || null, plugins: state.plugins }); state.diff = ''; setStatus(`Saved — backup ${result.backup}`); render(); } catch (e) { setStatus(`Save failed: ${e}`, true); } }
async function pluginAction() { const p = state.selectedPlugin; if (!p) return; const operation = p.installed ? 'update' : 'install'; confirmApply(`${operation === 'install' ? 'Install' : 'Update'} ${p.name}?`, `Source: ${p.source}. The operation will be recorded and can be reviewed in Activity.`, async () => { try { const command = operation === 'install' ? 'install_plugin' : 'update_plugin'; const result = await invoke(command, { owner: p.owner || 'ohmyzsh', repository: p.repo || p.name }); p.installed = true; p.currentCommit = result.commit || p.currentCommit || 'recorded'; setStatus(`${operation} complete`); render(); } catch (e) { setStatus(`${operation} failed: ${e}`, true); } }); }
async function togglePlugin() { const p = state.selectedPlugin; if (!p) return; if (!state.plugins.includes(p.name)) state.plugins.push(p.name); else state.plugins = state.plugins.filter(n => n !== p.name); p.enabled = state.plugins.includes(p.name); await previewConfig(); }
let searchTimer;
$('global-search').addEventListener('input', () => { if (state.section === 'discover') { renderDiscover(); clearTimeout(searchTimer); const query = $('global-search').value.trim(); if (query) { searchTimer = setTimeout(() => searchGitHub(query), 350); } } });
async function searchGitHub(query) { setStatus('Searching GitHub…'); try { const headers = { Accept: 'application/vnd.github+json' }; if (state.githubToken) headers.Authorization = `Bearer ${state.githubToken}`; const response = await fetch(`https://api.github.com/search/repositories?q=${encodeURIComponent(`${query} zsh plugin`)}&sort=stars&per_page=20`, { headers }); if (response.status === 403 || response.status === 429) { setStatus('GitHub rate limit reached — add a token in Settings', true); return; } if (!response.ok) throw new Error(`GitHub returned ${response.status}`); const payload = await response.json(); const existing = new Set(state.catalog.map(p => p.id)); for (const repo of payload.items || []) { const id = repo.full_name; if (!existing.has(id)) state.catalog.push({ id, name: repo.name, summary: repo.description || 'No description provided.', source: `GitHub · ${repo.full_name}`, kind: 'github', owner: repo.owner.login, repo: repo.name, installed: false, enabled: false, license: repo.license?.spdx_id || null }); } setStatus(`GitHub results updated at ${new Date().toLocaleTimeString()}`); renderDiscover(); } catch (e) { setStatus(`GitHub search failed: ${e.message}`, true); } } $('refresh-button').addEventListener('click', loadConfig); $('settings-button').addEventListener('click', () => { $('github-token').value = state.githubToken; $('settings-dialog').showModal(); }); $('settings-form').addEventListener('submit', async (e) => { if (e.submitter?.value !== 'save') return; state.githubToken = $('github-token').value.trim(); try { await invoke('set_github_token', { token: state.githubToken }); setStatus('GitHub token saved locally'); } catch { setStatus('Token was not saved', true); } }); document.querySelectorAll('.nav-item').forEach((el) => el.addEventListener('click', () => { state.section = el.dataset.section; document.querySelectorAll('.nav-item').forEach(n => n.classList.toggle('active', n === el)); render(); })); $('confirm-dialog').addEventListener('cancel', (e) => e.preventDefault()); loadConfig();
